permalink: /:categories/:title/
markdown: kramdown
plugins:
  - jekyll-redirect-from
exclude:
  - "vendor"
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
      starred: "false"
      music: "false"            